name: build

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu, macos]
        compiler: [clang++]
        # Ubuntu uses GCC which doesn't support coverage, and we want to compile with both GCC and Clang.
        include:
          - os: ubuntu
            compiler: g++
          - os: ubuntu
            compiler: clang++
            extra_compile_flags: "-DSLING_COVERAGE=ON"
            check_coverage: true
          - os: macos
            boostrap_command: true
    name: ${{matrix.os}} - ${{matrix.compiler}}
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        if: ${{matrix.boostrap_command}}
        run: |
          bash bootstrap_${{matrix.os}}.sh
      - name: make test
        run: |
          mkdir build
          pushd build
          CXX=${{matrix.compiler}} cmake .. -DSLING_SANITIZE=ON -DSLING_BUILD_CLI=ON ${{matrix.extra_compile_flags}}
          make -j2
          popd
          ./build/sling-test

      - name: print coverage
        if: ${{matrix.check_coverage}}
        run: |
          llvm-profdata-11 merge default.profraw -o default.profdata
          llvm-cov-11 report -ignore-filename-regex=\(tests\|extern\)/.* -show-region-summary=false --instr-profile default.profdata build/sling-test
