name: release

on:
  # Only trigger on release creation
  release:
    types:
      - created

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        addrsize: ["64"]
    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:

      - name: Bootstrap environment
        if: ${{matrix.bootstrap_script}}
        shell: bash
        run: |
          bash "${{matrix.bootstrap_script}}"

      - uses: secondlife/action-autobuild@v3
        with:
          addrsize: ${{ matrix.addrsize }}

      - uses: secondlife/action-autobuild-release@v1
        with:
          public: true
