name: release

on:
  # Only trigger on release creation
  release:
    types:
      - created

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2022]
        addrsize: ["64"]
    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v1

      - name: Install Mac Dependencies
        if: ${{ runner.os == 'macOS' }}
        shell: bash
        run: |
          bash bootstrap_macos.sh

      - uses: secondlife/action-autobuild@v3
        with:
          addrsize: ${{ matrix.addrsize }}
          cygwin-packages: flex bison

      - uses: secondlife/action-autobuild-release@v1
        with:
          public: true
